# Generated by Django 2.1 on 2019-08-31 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Brasindice',
            fields=[
                ('ID_Brasindice', models.IntegerField(primary_key=True, serialize=False)),
                ('Brasindice_PMF', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Brasindice_PF', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Simpro', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TUSS', models.CharField(max_length=50)),
                ('TISS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio_Medicamento',
            fields=[
                ('ID_Convenio_Medicamento', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Frasco',
            fields=[
                ('ID_Frasco', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantidade_Gotas_Saiu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Farmacologico',
            fields=[
                ('ID_Grupo_Farmacologico', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome_Grupo_Farmacologico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Prescricao',
            fields=[
                ('ID_Historico_Prescricao', models.IntegerField(primary_key=True, serialize=False)),
                ('FILESTREAM_Prescricao', models.CharField(max_length=100)),
                ('Data_Historico_Prescricao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lote_Medicamento_Entrada',
            fields=[
                ('ID_Lote_Medicamento_Entrada', models.IntegerField(primary_key=True, serialize=False)),
                ('Lote', models.IntegerField()),
                ('Data_Entrada', models.DateField()),
                ('Data_Validade', models.DateField()),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento_Cadastro',
            fields=[
                ('ID_Medicamento_Cadastro', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome_Medicamento', models.CharField(max_length=50)),
                ('Laboratorio', models.CharField(max_length=50)),
                ('Nome_do_Sal', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=50)),
                ('Grupo', models.CharField(max_length=50)),
                ('Quantidade', models.IntegerField()),
                ('ID_Brasindice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Codigo_Brasindice')),
                ('ID_Grupo_Farmacologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Grupo_Farmacologico')),
            ],
        ),
        migrations.CreateModel(
            name='Pilula',
            fields=[
                ('ID_Pilula', models.IntegerField(primary_key=True, serialize=False)),
                ('Valor_Saida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Quantidade_Gotas', models.IntegerField()),
                ('Etiqueta', models.IntegerField()),
                ('ID_Lote_Medicamento_Entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Lote_Medicamento_Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao_Medicamento',
            fields=[
                ('ID_Prescricao_Medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantidade_por_dia', models.IntegerField()),
                ('Periodo_inicio', models.DateField()),
                ('Periodo_fim', models.DateField()),
                ('Dosagem', models.IntegerField()),
                ('ID_Historico_Prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Historico_Prescricao')),
                ('ID_Medicamento_Cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Medicamento_Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Saida_Medicamento',
            fields=[
                ('ID_Saida_Medicamento', models.IntegerField(primary_key=True, serialize=False)),
                ('Data_Saida', models.DateTimeField()),
                ('Valor_Saida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Quantidade_de_Gotas', models.IntegerField()),
                ('ID_Prescricao_Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Prescricao_Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('ID_Setor', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome_Setor', models.CharField(max_length=50)),
                ('Descricao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('ID_Tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome_Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pilula',
            name='ID_Saida_Medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Saida_Medicamento'),
        ),
        migrations.AddField(
            model_name='pilula',
            name='ID_Setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Setor'),
        ),
        migrations.AddField(
            model_name='medicamento_cadastro',
            name='ID_Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Tipo'),
        ),
        migrations.AddField(
            model_name='lote_medicamento_entrada',
            name='ID_Medicamento_Cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Medicamento_Cadastro'),
        ),
        migrations.AddField(
            model_name='frasco',
            name='ID_Lote_Medicamento_Entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Lote_Medicamento_Entrada'),
        ),
        migrations.AddField(
            model_name='frasco',
            name='ID_Saida_Medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Saida_Medicamento'),
        ),
        migrations.AddField(
            model_name='frasco',
            name='ID_Setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Setor'),
        ),
        migrations.AddField(
            model_name='convenio_medicamento',
            name='ID_Medicamento_Cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.Medicamento_Cadastro'),
        ),
    ]
