# Generated by Django 2.1 on 2019-08-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalNoturno',
            fields=[
                ('id_adicional_noturno', models.IntegerField(db_column='ID_Adicional_Noturno', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
            ],
            options={
                'db_table': 'Adicional_Noturno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArquivoMedicoResponsavel',
            fields=[
                ('id_arquivo_medico_responsavel', models.IntegerField(db_column='ID_Arquivo_Medico_Responsavel', primary_key=True, serialize=False)),
                ('filestream_arquivo_medico_responsavel', models.CharField(db_column='FILESTREAM_Arquivo_Medico_Responsavel', max_length=200)),
                ('data', models.DateField(db_column='Data')),
            ],
            options={
                'db_table': 'Arquivo_Medico_Responsavel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AtendimentoMedicoPlantao',
            fields=[
                ('id_atendimento_medico_plantao', models.IntegerField(db_column='ID_Atendimento_Medico_Plantao', primary_key=True, serialize=False)),
                ('data_atendimento', models.DateField(db_column='Data_Atendimento')),
                ('filestream_atendimento_medico_plantao', models.CharField(db_column='FILESTREAM_Atendimento_Medico_Plantao', max_length=200)),
            ],
            options={
                'db_table': 'Atendimento_Medico_Plantao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.CharField(db_column='ID_Banco', max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
                ('dinheiro_dentro', models.DecimalField(db_column='Dinheiro_dentro', decimal_places=2, max_digits=8)),
                ('dinheiro_dentro_real', models.DecimalField(db_column='Dinheiro_dentro_Real', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Banco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroAcidenteTrabalho',
            fields=[
                ('id_cadastro_acidente_trabalho', models.IntegerField(db_column='ID_Cadastro_Acidente_Trabalho', primary_key=True, serialize=False)),
                ('motivo_acidente', models.CharField(db_column='Motivo_Acidente', max_length=120)),
                ('data_acidente', models.DateField(db_column='Data_Acidente')),
                ('data_abertura', models.DateField(db_column='Data_Abertura')),
                ('numero_cat', models.CharField(db_column='Numero_CAT', max_length=50)),
            ],
            options={
                'db_table': 'Cadastro_Acidente_Trabalho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroHd',
            fields=[
                ('id_cadastro_hd', models.IntegerField(db_column='ID_Cadastro_HD', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(db_column='Data_Fim')),
                ('senha_provisoria', models.CharField(db_column='Senha_Provisoria', max_length=100)),
                ('data_validade_senha', models.DateField(db_column='Data_Validade_Senha')),
            ],
            options={
                'db_table': 'Cadastro_HD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroInternacao',
            fields=[
                ('id_cadastro_internacao', models.IntegerField(db_column='ID_Cadastro_Internacao', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(blank=True, db_column='Data_Fim', null=True)),
                ('valor_caucao', models.DecimalField(db_column='Valor_Caucao', decimal_places=2, max_digits=8)),
                ('recomendacao_medica', models.IntegerField(db_column='Recomendacao_Medica')),
                ('filestream_documento_recomendacao_medica', models.CharField(db_column='FILESTREAM_Documento_Recomendacao_Medica', max_length=200)),
                ('involuntaria', models.IntegerField(db_column='Involuntaria')),
                ('dependente_quimico', models.IntegerField(db_column='Dependente_Quimico')),
                ('filestream_documento_ordem_judicial', models.CharField(blank=True, db_column='FILESTREAM_Documento_Ordem_Judicial', max_length=200, null=True)),
                ('data_aviso_ordem_judicial', models.DateTimeField(blank=True, db_column='Data_Aviso_Ordem_Judicial', null=True)),
                ('ordem_judicial', models.IntegerField(blank=True, db_column='Ordem_Judicial', null=True)),
                ('filestream_documento_termo_ciencia', models.CharField(blank=True, db_column='FILESTREAM_Documento_Termo_Ciencia', max_length=200, null=True)),
                ('filestream_documento_familia_de_acordo', models.CharField(blank=True, db_column='FILESTREAM_Documento_Familia_de_Acordo', max_length=200, null=True)),
                ('senha_provisoria', models.CharField(db_column='Senha_Provisoria', max_length=50)),
                ('data_validade_senha', models.CharField(db_column='Data_Validade_Senha', max_length=50)),
                ('motivo_alta', models.CharField(blank=True, db_column='Motivo_Alta', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cadastro_Internacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CadastroProduto',
            fields=[
                ('id_cadastro_produto', models.IntegerField(db_column='ID_Cadastro_Produto', primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(db_column='Nome_Produto', max_length=50)),
                ('descricao', models.CharField(db_column='Descricao', max_length=100)),
                ('quantidade_minima', models.IntegerField(db_column='Quantidade_Minima')),
            ],
            options={
                'db_table': 'Cadastro_Produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CargoFuncionario',
            fields=[
                ('id_cargo_funcionario', models.IntegerField(db_column='ID_Cargo_Funcionario', primary_key=True, serialize=False)),
                ('nome_cargo', models.CharField(db_column='Nome_Cargo', max_length=50)),
            ],
            options={
                'db_table': 'Cargo_Funcionario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id_categoria_produto', models.IntegerField(db_column='ID_Categoria_Produto', primary_key=True, serialize=False)),
                ('nome_categoria_produto', models.CharField(db_column='Nome_Categoria_Produto', max_length=50)),
            ],
            options={
                'db_table': 'Categoria_Produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.IntegerField(db_column='ID_Certificado', primary_key=True, serialize=False)),
                ('registro_certificado', models.CharField(db_column='Registro_Certificado', max_length=30)),
                ('vencimento_certificado', models.DateField(db_column='Vencimento_Certificado')),
                ('verificado', models.IntegerField(db_column='Verificado')),
                ('protocolo_cnes', models.CharField(db_column='Protocolo_CNES', max_length=50)),
            ],
            options={
                'db_table': 'Certificado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id_cid', models.IntegerField(db_column='ID_CID', primary_key=True, serialize=False)),
                ('nome_cid', models.CharField(db_column='Nome_CID', max_length=50)),
                ('numero_cadastrado', models.CharField(db_column='Numero_Cadastrado', max_length=50)),
            ],
            options={
                'db_table': 'CID',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cipa',
            fields=[
                ('id_cipa', models.IntegerField(db_column='ID_CIPA', primary_key=True, serialize=False)),
                ('cargo_cipa', models.CharField(db_column='Cargo_CIPA', max_length=50)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(db_column='Data_Fim')),
            ],
            options={
                'db_table': 'CIPA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoBrasindice',
            fields=[
                ('id_codigo_brasindice', models.IntegerField(db_column='ID_Codigo_Brasindice', primary_key=True, serialize=False)),
                ('brasindice_pmf', models.DecimalField(db_column='Brasindice_PMF', decimal_places=2, max_digits=8)),
                ('brasindice_pf', models.DecimalField(db_column='Brasindice_PF', decimal_places=2, max_digits=8)),
                ('simpro', models.DecimalField(db_column='Simpro', decimal_places=2, max_digits=8)),
                ('tuss', models.CharField(db_column='TUSS', max_length=50)),
                ('tiss', models.CharField(db_column='TISS', max_length=50)),
            ],
            options={
                'db_table': 'Codigo_brasindice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id_conselho_classe', models.IntegerField(db_column='ID_Conselho_Classe', primary_key=True, serialize=False)),
                ('tipo_conselho_classe', models.CharField(db_column='Tipo_Conselho_Classe', max_length=50)),
            ],
            options={
                'db_table': 'Conselho_Classe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.IntegerField(db_column='ID_Consulta', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('confirmado', models.IntegerField(db_column='Confirmado')),
                ('consultado', models.IntegerField(db_column='Consultado')),
            ],
            options={
                'db_table': 'Consulta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConsultaConvenio',
            fields=[
                ('id_consulta_convenio', models.IntegerField(db_column='ID_Consulta_Convenio', primary_key=True, serialize=False)),
                ('valor_consulta', models.DecimalField(db_column='Valor_Consulta', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Consulta_Convenio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ContratoConvenio',
            fields=[
                ('id_contrato_convenio', models.IntegerField(db_column='ID_Contrato_Convenio', primary_key=True, serialize=False)),
                ('filestream_contrato_convenio', models.CharField(db_column='FILESTREAM_Contrato_Convenio', max_length=200)),
                ('tipo_contrato', models.CharField(db_column='Tipo_Contrato', max_length=50)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(db_column='Data_Fim')),
                ('valor_mensal', models.DecimalField(blank=True, db_column='Valor_Mensal', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Contrato_Convenio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id_controle', models.IntegerField(db_column='ID_Controle', primary_key=True, serialize=False)),
                ('previsao_estoque', models.IntegerField(db_column='Previsao_Estoque')),
                ('status_prescricao', models.CharField(db_column='Status_Prescricao', max_length=50)),
                ('cobertura_convenio', models.CharField(db_column='Cobertura_Convenio', max_length=50)),
            ],
            options={
                'db_table': 'Controle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id_convenio', models.IntegerField(db_column='ID_Convenio', primary_key=True, serialize=False)),
                ('nome_convenio', models.CharField(db_column='Nome_Convenio', max_length=50)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=50)),
            ],
            options={
                'db_table': 'Convenio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConvenioMedicamento',
            fields=[
                ('id_convenio_medicamento', models.IntegerField(db_column='ID_Convenio_medicamento', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Convenio_Medicamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DadosHospital',
            fields=[
                ('id_cnpj', models.CharField(db_column='ID_CNPJ', max_length=50, primary_key=True, serialize=False)),
                ('end_rua', models.CharField(db_column='End_Rua', max_length=100)),
                ('end_numero', models.IntegerField(db_column='End_Numero')),
                ('end_cep', models.CharField(db_column='End_CEP', max_length=10)),
                ('end_complemento', models.CharField(db_column='End_Complemento', max_length=100)),
                ('telefone', models.CharField(db_column='Telefone', max_length=50)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
            ],
            options={
                'db_table': 'Dados_Hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DescontosGratificacoes',
            fields=[
                ('id_descontos_gratificacoes', models.IntegerField(db_column='ID_Descontos_Gratificacoes', primary_key=True, serialize=False)),
                ('mes', models.IntegerField(db_column='Mes')),
                ('gratificacao', models.IntegerField(db_column='Gratificacao')),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Descontos_Gratificacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiariasConvenio',
            fields=[
                ('id_diarias_convenio', models.IntegerField(db_column='ID_Diarias_Convenio', primary_key=True, serialize=False)),
                ('valor_diarias_convenio', models.DecimalField(db_column='Valor_Diarias_Convenio', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Diarias_Convenio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DispMedConsulta',
            fields=[
                ('id_disp_med_consulta', models.IntegerField(db_column='ID_Disp_Med_Consulta', primary_key=True, serialize=False)),
                ('data_disp_med_consulta', models.DateField(db_column='Data_Disp_Med_Consulta')),
                ('periodo_consulta', models.CharField(db_column='Periodo_Consulta', max_length=50)),
                ('sala_consulta', models.IntegerField(db_column='Sala_Consulta')),
            ],
            options={
                'db_table': 'Disp_Med_Consulta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeHorarioMultidisciplinar',
            fields=[
                ('id_horario', models.IntegerField(db_column='ID_Horario', primary_key=True, serialize=False)),
                ('horario_inicio', models.DateTimeField(db_column='Horario_Inicio')),
                ('horario_fim', models.DateTimeField(db_column='Horario_Fim')),
            ],
            options={
                'db_table': 'Disponibilidade_Horario_Multidisciplinar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DoacaoPilula',
            fields=[
                ('id_doacao_pilula', models.IntegerField(db_column='ID_Doacao_Pilula', primary_key=True, serialize=False)),
                ('motivo', models.CharField(db_column='Motivo', max_length=300)),
                ('nome_recebedor_doacao', models.CharField(db_column='Nome_Recebedor_Doacao', max_length=300)),
                ('cnpj_cpf', models.CharField(db_column='CNPJ_CPF', max_length=50)),
            ],
            options={
                'db_table': 'Doacao_Pilula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.IntegerField(db_column='ID_Emprestimo', primary_key=True, serialize=False)),
                ('valor_total_emprestimo', models.DecimalField(db_column='Valor_Total_Emprestimo', decimal_places=2, max_digits=8)),
                ('valor_pago', models.DecimalField(db_column='Valor_Pago', decimal_places=2, max_digits=8)),
                ('qtd_prestacoes', models.IntegerField(db_column='Qtd_Prestacoes')),
                ('data_inicio', models.DateField(db_column='Data_inicio')),
            ],
            options={
                'db_table': 'Emprestimo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnfermagemPlantao',
            fields=[
                ('id_atendimento_enfermagem_plantao', models.IntegerField(db_column='ID_Atendimento_Enfermagem_Plantao', primary_key=True, serialize=False)),
                ('data_atendimento', models.DateField(db_column='Data_Atendimento')),
                ('filestream_enfermagem_plantao', models.CharField(db_column='FILESTREAM_Enfermagem_Plantao', max_length=200)),
            ],
            options={
                'db_table': 'Enfermagem_Plantao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EscalaMedicoPlantao',
            fields=[
                ('id_escala_medico_plantao', models.IntegerField(db_column='ID_Escala_Medico_Plantao', primary_key=True, serialize=False)),
                ('data', models.DateField(db_column='Data')),
                ('periodo', models.CharField(db_column='Periodo', max_length=50)),
            ],
            options={
                'db_table': 'Escala_Medico_Plantao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id_especialidade', models.IntegerField(db_column='ID_Especialidade', primary_key=True, serialize=False)),
                ('nome_especialidade', models.CharField(db_column='Nome_Especialidade', max_length=50)),
            ],
            options={
                'db_table': 'Especialidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.IntegerField(db_column='ID_Estado_Civil', primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(db_column='Estado_Civil', max_length=30)),
            ],
            options={
                'db_table': 'Estado_Civil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.IntegerField(db_column='ID_Estoque', primary_key=True, serialize=False)),
                ('id_produto', models.IntegerField(db_column='ID_Produto')),
                ('lote', models.CharField(db_column='Lote', max_length=50)),
                ('valor', models.CharField(db_column='Valor', max_length=50)),
                ('data_entrada', models.DateField(db_column='Data_Entrada')),
                ('data_saida', models.DateField(blank=True, db_column='Data_Saida', null=True)),
            ],
            options={
                'db_table': 'Estoque',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id_ferias', models.IntegerField(db_column='ID_Ferias', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(db_column='Data_Fim')),
                ('periodo_aquisitivo', models.CharField(db_column='Periodo_Aquisitivo', max_length=50)),
                ('gozado', models.IntegerField(db_column='Gozado')),
                ('valor_ferias', models.DecimalField(db_column='Valor_Ferias', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Ferias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.IntegerField(db_column='ID_Fornecedor', primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(db_column='Nome_Fornecedor', max_length=50)),
                ('end_rua', models.CharField(db_column='End_Rua', max_length=50)),
                ('end_num', models.IntegerField(db_column='End_Num')),
                ('end_cep', models.CharField(db_column='End_CEP', max_length=50)),
                ('end_complemento', models.CharField(db_column='End_Complemento', max_length=50)),
                ('telefone', models.CharField(db_column='Telefone', max_length=50)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=50)),
                ('tel', models.CharField(db_column='Tel', max_length=50)),
            ],
            options={
                'db_table': 'Fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Frasco',
            fields=[
                ('id_frasco', models.IntegerField(db_column='ID_Frasco', primary_key=True, serialize=False)),
                ('quantidade_gotas_saida', models.IntegerField(db_column='Quantidade_Gotas_Saida')),
            ],
            options={
                'db_table': 'Frasco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.IntegerField(db_column='ID_Funcionario', primary_key=True, serialize=False)),
                ('data_admissao', models.DateField(db_column='Data_Admissao')),
                ('conta_cef', models.CharField(db_column='Conta_CEF', max_length=50)),
                ('carga_horaria_tipo', models.CharField(db_column='Carga_Horaria_Tipo', max_length=50)),
                ('carga_horaria_intervalo', models.TimeField(db_column='Carga_Horaria_Intervalo')),
                ('pis', models.IntegerField(db_column='PIS')),
                ('ctps_numero', models.BigIntegerField(db_column='CTPS_Numero')),
                ('ctps_serie', models.BigIntegerField(db_column='CTPS_Serie')),
                ('possui_epi', models.IntegerField(db_column='Possui_EPI')),
                ('vacina_hepatite', models.DateField(blank=True, db_column='Vacina_Hepatite', null=True)),
                ('vacina_triplice_viral', models.DateField(blank=True, db_column='Vacina_Triplice_Viral', null=True)),
                ('vacina_duplo_adulto', models.DateField(blank=True, db_column='Vacina_Duplo_Adulto', null=True)),
                ('valor_max_emprestimo', models.IntegerField(db_column='Valor_Max_Emprestimo')),
            ],
            options={
                'db_table': 'Funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id_glosa', models.IntegerField(db_column='ID_Glosa', primary_key=True, serialize=False)),
                ('valor_glosado', models.DecimalField(db_column='Valor_Glosado', decimal_places=2, max_digits=8)),
                ('filestream_justificativa_convenio', models.CharField(db_column='FILESTREAM_Justificativa_Conv�nio', max_length=200)),
                ('filestream_justificativa_aicp', models.CharField(blank=True, db_column='FILESTREAM_Justificativa_AICP', max_length=200, null=True)),
                ('justificativa_glosa_aceita', models.IntegerField(blank=True, db_column='Justificativa_Glosa_Aceita', null=True)),
                ('data_prazo_resposta', models.DateField(db_column='Data_Prazo_Resposta')),
                ('glosa_definitiva', models.IntegerField(blank=True, db_column='Glosa_Definitiva', null=True)),
            ],
            options={
                'db_table': 'Glosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrauInstrucao',
            fields=[
                ('id_grau_instrucao', models.IntegerField(db_column='ID_Grau_Instrucao', primary_key=True, serialize=False)),
                ('nome_grau_instrucao', models.CharField(db_column='Nome_Grau_Instrucao', max_length=50)),
            ],
            options={
                'db_table': 'Grau_Instrucao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoFarmacologico',
            fields=[
                ('id_grupo_farmacologico', models.IntegerField(db_column='ID_Grupo_Farmacologico', primary_key=True, serialize=False)),
                ('nome_grupo_farmacologico', models.CharField(db_column='Nome_Grupo_Farmacologico', max_length=100)),
            ],
            options={
                'db_table': 'Grupo_Farmacologico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtestado',
            fields=[
                ('id_atestado', models.IntegerField(db_column='ID_Atestado', primary_key=True, serialize=False)),
                ('filestream_atestado', models.CharField(db_column='FILESTREAM_Atestado', max_length=200)),
                ('data_atestado', models.DateField(db_column='Data_Atestado')),
            ],
            options={
                'db_table': 'Historico_Atestado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoDieta',
            fields=[
                ('id_dieta', models.IntegerField(db_column='ID_Dieta', primary_key=True, serialize=False)),
                ('data_dieta', models.DateField(db_column='Data_Dieta')),
                ('filestream_dieta', models.CharField(db_column='FILESTREAM_Dieta', max_length=200)),
            ],
            options={
                'db_table': 'Historico_Dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoExame',
            fields=[
                ('id_historico_exame', models.IntegerField(db_column='ID_Historico_Exame', primary_key=True, serialize=False)),
                ('data_exame', models.DateField(db_column='Data_Exame')),
                ('filestream_historico_exame', models.CharField(db_column='FILESTREAM_Historico_Exame', max_length=200)),
            ],
            options={
                'db_table': 'Historico_Exame',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoMedicoResponsavel',
            fields=[
                ('id_atendimento_historico_medico_responsavel', models.IntegerField(db_column='ID_Atendimento_Historico_Medico_Responsavel', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(blank=True, db_column='Data_Fim', null=True)),
            ],
            options={
                'db_table': 'Historico_Medico_Responsavel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrescricao',
            fields=[
                ('id_historico_prescricao', models.IntegerField(db_column='ID_Historico_Prescricao', primary_key=True, serialize=False)),
                ('filestream_prescricao', models.CharField(db_column='FILESTREAM_Prescricao', max_length=200)),
                ('data_historico_prescricao', models.DateField(db_column='Data_Historico_Prescricao')),
            ],
            options={
                'db_table': 'Historico_Prescricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id_hora_extra', models.IntegerField(db_column='ID_Hora_Extra', primary_key=True, serialize=False)),
                ('mes_hora_extra', models.CharField(db_column='Mes_Hora_Extra', max_length=2)),
                ('ano_hora_extra', models.CharField(db_column='Ano_Hora_Extra', max_length=4)),
                ('quantidade_hora_extra', models.IntegerField(db_column='Quantidade_Hora_Extra')),
                ('justificativa', models.CharField(db_column='Justificativa', max_length=50)),
            ],
            options={
                'db_table': 'Hora_Extra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensNotaFiscal',
            fields=[
                ('id_itens_nota_fiscal', models.IntegerField(db_column='ID_Itens_Nota_Fiscal', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Itens_Nota_Fiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leito',
            fields=[
                ('id_leito', models.IntegerField(db_column='ID_Leito', primary_key=True, serialize=False)),
                ('num_leito', models.IntegerField(db_column='Num_leito')),
            ],
            options={
                'db_table': 'Leito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteMedicamentoEntrada',
            fields=[
                ('id_lote_medicamento_entrada', models.IntegerField(db_column='ID_Lote_Medicamento_Entrada', primary_key=True, serialize=False)),
                ('lote', models.IntegerField(db_column='Lote')),
                ('data_entrada', models.DateField(db_column='Data_Entrada')),
                ('data_validade', models.DateField(db_column='Data_Validade')),
                ('data_fabricacao', models.DateField(db_column='Data_Fabricacao')),
                ('valor_compra_medicamento', models.DecimalField(db_column='Valor_Compra_Medicamento', decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
            ],
            options={
                'db_table': 'Lote_Medicamento_Entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LotePagamento',
            fields=[
                ('id_lote_pagamento', models.IntegerField(db_column='ID_Lote_Pagamento', primary_key=True, serialize=False)),
                ('lote_convenio', models.CharField(blank=True, db_column='Lote_Convenio', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Lote_Pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentoCadastro',
            fields=[
                ('id_medicamento_cadastro', models.IntegerField(db_column='ID_Medicamento_Cadastro', primary_key=True, serialize=False)),
                ('nome_medicamento', models.CharField(db_column='Nome_Medicamento', max_length=50)),
                ('laboratorio', models.CharField(db_column='Laboratorio', max_length=50)),
                ('grupo', models.CharField(db_column='Grupo', max_length=50)),
                ('descricao', models.CharField(db_column='Descricao', max_length=50)),
                ('quantidade_gotas', models.IntegerField(blank=True, db_column='Quantidade_Gotas', null=True)),
            ],
            options={
                'db_table': 'Medicamento_Cadastro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentoEstoque',
            fields=[
                ('id_medicamento_estoque', models.IntegerField(db_column='ID_Medicamento_Estoque', primary_key=True, serialize=False)),
                ('quantidade_total', models.IntegerField(db_column='Quantidade_Total')),
                ('quantidade_farmacia', models.IntegerField(db_column='Quantidade_Farmacia')),
            ],
            options={
                'db_table': 'Medicamento_Estoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamentoFamilia',
            fields=[
                ('id_medicamento_familia', models.IntegerField(db_column='ID_Medicamento_Familia', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
            ],
            options={
                'db_table': 'Medicamento_Familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.IntegerField(db_column='ID_Medico', primary_key=True, serialize=False)),
                ('crm', models.CharField(db_column='CRM', max_length=50)),
            ],
            options={
                'db_table': 'Medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoConvenio',
            fields=[
                ('id_medico_convenio', models.IntegerField(db_column='ID_Medico_Convenio', primary_key=True, serialize=False)),
                ('valor_consulta_especial', models.DecimalField(blank=True, db_column='Valor_Consulta_Especial', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Medico_Convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedidaCorretiva',
            fields=[
                ('id_medida_corretiva', models.IntegerField(db_column='ID_Medida_Corretiva', primary_key=True, serialize=False)),
                ('fato_observado', models.CharField(db_column='Fato_Observado', max_length=200)),
                ('data_medida_corretiva', models.DateField(db_column='Data_Medida_Corretiva')),
            ],
            options={
                'db_table': 'Medida_Corretiva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MotivoSaidaPilula',
            fields=[
                ('id_motivo_saida_pilula', models.IntegerField(db_column='ID_Motivo_Saida_Pilula', primary_key=True, serialize=False)),
                ('nome_motivo_saida_pilula', models.CharField(db_column='Nome_Motivo_Saida_Pilula', max_length=50)),
            ],
            options={
                'db_table': 'Motivo_Saida_Pilula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NomeSal',
            fields=[
                ('id_nome_sal', models.IntegerField(db_column='ID_Nome_SAL', primary_key=True, serialize=False)),
                ('descricao_sal', models.CharField(db_column='Descricao_SAL', max_length=50)),
            ],
            options={
                'db_table': 'Nome_SAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id_nota_fiscal', models.CharField(db_column='ID_Nota_Fiscal', max_length=50, primary_key=True, serialize=False)),
                ('mes_competencia', models.CharField(db_column='Mes_Competencia', max_length=2)),
                ('ano_competencia', models.CharField(db_column='Ano_Competencia', max_length=4)),
                ('razao_social', models.CharField(db_column='Razao_Social', max_length=50)),
                ('data_expedicao', models.DateField(blank=True, db_column='Data_Expedicao', null=True)),
            ],
            options={
                'db_table': 'Nota_Fiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.IntegerField(db_column='ID_Paciente', primary_key=True, serialize=False)),
                ('n_carteira', models.CharField(db_column='N_Carteira', max_length=50)),
                ('validade_carteira', models.DateField(db_column='Validade_Carteira')),
                ('restricao_internacao', models.IntegerField(db_column='Restricao_Internacao')),
                ('motivo_restricao', models.CharField(blank=True, db_column='Motivo_Restricao', max_length=500, null=True)),
                ('nome_pai', models.CharField(blank=True, db_column='Nome_Pai', max_length=50, null=True)),
                ('nome_mae', models.CharField(blank=True, db_column='Nome_Mae', max_length=50, null=True)),
                ('procedencia', models.CharField(blank=True, db_column='Procedencia', max_length=50, null=True)),
                ('medicamento_familiar', models.IntegerField(db_column='Medicamento_Familiar')),
            ],
            options={
                'db_table': 'Paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagConvenioConsulta',
            fields=[
                ('id_pag_convenio_consulta', models.IntegerField(db_column='ID_Pag_Convenio_Consulta', primary_key=True, serialize=False)),
                ('data_fim_resposta', models.DateField(blank=True, db_column='Data_Fim_Resposta', null=True)),
                ('data_fim_pedido', models.DateField(blank=True, db_column='Data_Fim_Pedido', null=True)),
                ('data_pedido_autorizacao', models.DateField(blank=True, db_column='Data_Pedido_Autorizacao', null=True)),
                ('data_resposta', models.DateField(blank=True, db_column='Data_Resposta', null=True)),
                ('data_estimativa_resposta', models.DateField(blank=True, db_column='Data_Estimativa_Resposta', null=True)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_convenio', models.DecimalField(blank=True, db_column='Valor_Convenio', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Pag_Convenio_Consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagConvenioDieta',
            fields=[
                ('id_pag_convenio_dieta', models.IntegerField(db_column='ID_Pag_Convenio_Dieta', primary_key=True, serialize=False)),
                ('data_fim_resposta', models.DateField(blank=True, db_column='Data_Fim_Resposta', null=True)),
                ('data_fim_pedido', models.DateField(blank=True, db_column='Data_Fim_Pedido', null=True)),
                ('data_pedido_autorizacao', models.DateField(blank=True, db_column='Data_Pedido_Autorizacao', null=True)),
                ('data_resposta', models.DateField(blank=True, db_column='Data_Resposta', null=True)),
                ('data_estimativa_resposta', models.DateField(blank=True, db_column='Data_Estimativa_Resposta', null=True)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('date_pag', models.DateField(blank=True, db_column='Date_Pag', null=True)),
                ('valor_convenio', models.DecimalField(blank=True, db_column='Valor_Convenio', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Pag_Convenio_Dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagConvenioHd',
            fields=[
                ('id_pag_convenio_hd', models.IntegerField(db_column='ID_Pag_Convenio_HD', primary_key=True, serialize=False)),
                ('qtd_dias_pedidos', models.IntegerField(db_column='Qtd_Dias_Pedidos')),
                ('data_fim_resposta', models.DateField(blank=True, db_column='Data_Fim_Resposta', null=True)),
                ('data_fim_pedido', models.DateField(blank=True, db_column='Data_Fim_Pedido', null=True)),
                ('data_pedido_autorizacao', models.DateField(blank=True, db_column='Data_Pedido_Autorizacao', null=True)),
                ('data_resposta', models.DateField(blank=True, db_column='Data_Resposta', null=True)),
                ('data_estimativa_resposta', models.DateField(blank=True, db_column='Data_Estimativa_Resposta', null=True)),
                ('qtd_dias_autorizados', models.IntegerField(blank=True, db_column='Qtd_Dias_Autorizados', null=True)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_convenio', models.DecimalField(blank=True, db_column='Valor_Convenio', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Pag_Convenio_HD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagConvenioInternacao',
            fields=[
                ('id_pag_convenio_internacao', models.IntegerField(db_column='ID_Pag_Convenio_Internacao', primary_key=True, serialize=False)),
                ('data_inicio_periodo', models.DateField(blank=True, db_column='Data_Inicio_Periodo', null=True)),
                ('data_final_periodo', models.DateField(blank=True, db_column='Data_Final_Periodo', null=True)),
                ('data_final_pedido', models.DateField(blank=True, db_column='Data_Final_Pedido', null=True)),
                ('data_pedido_autorizacao', models.DateField(blank=True, db_column='Data_Pedido_Autorizacao', null=True)),
                ('data_resposta', models.DateField(blank=True, db_column='Data_Resposta', null=True)),
                ('data_estimativa_resposta', models.DateField(blank=True, db_column='Data_Estimativa_Resposta', null=True)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_convenio', models.DecimalField(blank=True, db_column='Valor_Convenio', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Pag_Convenio_Internacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagConvenioMedicamento',
            fields=[
                ('id_pag_convenio_medicamento', models.IntegerField(db_column='ID_Pag_Convenio_Medicamento', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('data_pedido_autorizacao', models.DateField(blank=True, db_column='Data_Pedido_Autorizacao', null=True)),
                ('data_resposta', models.DateField(blank=True, db_column='Data_Resposta', null=True)),
                ('data_estimativa_resposta', models.DateField(blank=True, db_column='Data_Estimativa_Resposta', null=True)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_convenio', models.DecimalField(blank=True, db_column='Valor_Convenio', decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Pag_Convenio_Medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagParticularConsulta',
            fields=[
                ('id_pag_particular_consulta', models.IntegerField(db_column='ID_Pag_Particular_Consulta', primary_key=True, serialize=False)),
                ('data_previsao_pag_consulta', models.DateField(blank=True, db_column='Data_Previsao_Pag_Consulta', null=True)),
                ('data_pag_consulta', models.DateField(blank=True, db_column='Data_Pag_Consulta', null=True)),
                ('valor_particular_consulta', models.DecimalField(db_column='Valor_Particular_Consulta', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Pag_Particular_Consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagParticularDieta',
            fields=[
                ('id_pag_particular_dieta', models.IntegerField(db_column='ID_Pag_Particular_Dieta', primary_key=True, serialize=False)),
                ('data_previsao_pag_dieta', models.DateField(blank=True, db_column='Data_Previsao_Pag_Dieta', null=True)),
                ('data_pag_particular_dieta', models.DateField(blank=True, db_column='Data_Pag_Particular_Dieta', null=True)),
                ('valor_pag_particular_dieta', models.DecimalField(db_column='Valor_Pag_Particular_Dieta', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Pag_Particular_Dieta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagParticularHd',
            fields=[
                ('id_pag_particular_hd', models.IntegerField(db_column='ID_Pag_Particular_HD', primary_key=True, serialize=False)),
                ('data_previsao_pag_hd', models.DateField(blank=True, db_column='Data_Previsao_Pag_HD', null=True)),
                ('data_pag_hd', models.DateField(blank=True, db_column='Data_Pag_HD', null=True)),
                ('valor_particular_hd', models.DecimalField(db_column='Valor_Particular_HD', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Pag_Particular_HD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagParticularInternacao',
            fields=[
                ('id_pag_particular_internacao', models.IntegerField(db_column='ID_Pag_Particular_Internacao', primary_key=True, serialize=False)),
                ('data_previsao', models.DateField(blank=True, db_column='Data_Previsao', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_particular', models.DecimalField(db_column='Valor_Particular', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Pag_Particular_Internacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagParticularMed',
            fields=[
                ('id_pag_particular_med', models.IntegerField(db_column='ID_Pag_Particular_Med', primary_key=True, serialize=False)),
                ('data_previsao_pag', models.DateField(blank=True, db_column='Data_Previsao_Pag', null=True)),
                ('data_pag', models.DateField(blank=True, db_column='Data_Pag', null=True)),
                ('valor_particular', models.DecimalField(db_column='Valor_Particular', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'Pag_Particular_Med',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id_pedido_compra', models.IntegerField(db_column='ID_Pedido_Compra', primary_key=True, serialize=False)),
                ('autorizado', models.IntegerField(db_column='Autorizado')),
                ('motivo', models.CharField(db_column='Motivo', max_length=50)),
                ('numero_pedido', models.IntegerField(db_column='Numero_Pedido')),
            ],
            options={
                'db_table': 'Pedido_Compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_cpf', models.CharField(db_column='ID_CPF', max_length=20, primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(db_column='Nome_Pessoa', max_length=200)),
                ('sexo_masculino', models.IntegerField(db_column='Sexo_Masculino')),
                ('falecido', models.IntegerField(db_column='Falecido')),
                ('data_nascimento', models.DateField(blank=True, db_column='Data_Nascimento', null=True)),
                ('telefone_residencial', models.CharField(blank=True, db_column='Telefone_Residencial', max_length=20, null=True)),
                ('telefone_celular', models.CharField(db_column='Telefone_Celular', max_length=20)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('rg', models.CharField(db_column='RG', max_length=20)),
                ('rg_orgao_expeditor', models.CharField(db_column='RG_Orgao_Expeditor', max_length=50)),
                ('rg_uf', models.CharField(db_column='RG_UF', max_length=2)),
                ('rg_data_emissao', models.DateField(db_column='RG_Data_Emissao')),
                ('naturalidade', models.CharField(blank=True, db_column='Naturalidade', max_length=50, null=True)),
                ('uf', models.CharField(blank=True, db_column='UF', max_length=50, null=True)),
                ('nacionalidade', models.CharField(blank=True, db_column='Nacionalidade', max_length=50, null=True)),
                ('profissao', models.CharField(db_column='Profissao', max_length=50)),
                ('foto', models.CharField(db_column='Foto', max_length=200)),
                ('conjuge', models.CharField(db_column='Conjuge', max_length=200)),
                ('endereco_rua', models.CharField(db_column='Endereco_Rua', max_length=100)),
                ('endereco_complemento', models.IntegerField(db_column='Endereco_Complemento')),
                ('endereco_cep', models.CharField(db_column='Endereco_CEP', max_length=50)),
                ('endereco_estado', models.CharField(db_column='Endereco_Estado', max_length=100)),
                ('endereco_cidade', models.CharField(db_column='Endereco_Cidade', max_length=100)),
                ('endereco_bairro', models.CharField(db_column='Endereco_Bairro', max_length=100)),
            ],
            options={
                'db_table': 'Pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaComDeficiencia',
            fields=[
                ('id_pcd', models.IntegerField(db_column='ID_PCD', primary_key=True, serialize=False)),
                ('tipo_deficiencia', models.CharField(db_column='Tipo_Deficiencia', max_length=50)),
            ],
            options={
                'db_table': 'Pessoa_Com_Deficiencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilula',
            fields=[
                ('id_pilula', models.IntegerField(db_column='ID_Pilula', primary_key=True, serialize=False)),
                ('etiqueta', models.IntegerField(db_column='Etiqueta')),
            ],
            options={
                'db_table': 'Pilula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescricaoMedicamento',
            fields=[
                ('id_prescricao_medicamento', models.IntegerField(db_column='ID_Prescricao_Medicamento', primary_key=True, serialize=False)),
                ('quantidade_por_dia', models.IntegerField(db_column='Quantidade_por_dia')),
                ('periodo_inicio', models.DateTimeField(db_column='Periodo_inicio')),
                ('periodo_fim', models.DateTimeField(db_column='Periodo_fim')),
                ('dosagem', models.IntegerField(db_column='Dosagem')),
            ],
            options={
                'db_table': 'Prescricao_Medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresencaHd',
            fields=[
                ('id_presenca_hd', models.IntegerField(db_column='ID_Presenca_HD', primary_key=True, serialize=False)),
                ('data_presenca_hd', models.DateField(db_column='Data_Presenca_HD')),
            ],
            options={
                'db_table': 'Presenca_HD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresencaTreinamento',
            fields=[
                ('id_presenca_treinamento', models.IntegerField(db_column='ID_Presenca_Treinamento', primary_key=True, serialize=False)),
                ('atraso', models.IntegerField(db_column='Atraso')),
            ],
            options={
                'db_table': 'Presenca_Treinamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrestacaoPagaEmprestimo',
            fields=[
                ('id_prestacao_paga_emprestimo', models.IntegerField(db_column='ID_Prestacao_Paga_Emprestimo', primary_key=True, serialize=False)),
                ('valor_pago_prestacao', models.DecimalField(db_column='Valor_Pago_Prestacao', decimal_places=2, max_digits=8)),
                ('data_pagamento_prestacao', models.DateField(db_column='Data_Pagamento_Prestacao')),
            ],
            options={
                'db_table': 'Prestacao_Paga_Emprestimo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.CharField(db_column='ID_Recibo', max_length=50, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=2, max_digits=8)),
                ('cheque', models.IntegerField(blank=True, db_column='Cheque', null=True)),
                ('destinario', models.CharField(db_column='Destinario', max_length=50)),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=50, null=True)),
                ('data', models.DateField(db_column='Data')),
                ('nome_nota', models.CharField(db_column='Nome_Nota', max_length=50)),
            ],
            options={
                'db_table': 'Recibo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroLigacaoPaciente',
            fields=[
                ('id_registro_ligacao_paciente', models.IntegerField(db_column='ID_Registro_Ligacao_Paciente', primary_key=True, serialize=False)),
                ('motivo', models.CharField(db_column='Motivo', max_length=120)),
            ],
            options={
                'db_table': 'Registro_Ligacao_Paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsavelHistorico',
            fields=[
                ('id_reponsabilidade', models.IntegerField(db_column='ID_Reponsabilidade', primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(db_column='Data_Inicio')),
                ('data_fim', models.DateField(db_column='Data_Fim')),
            ],
            options={
                'db_table': 'Responsavel_Historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoupaPaciente',
            fields=[
                ('id_roupa_paciente', models.IntegerField(db_column='ID_Roupa_Paciente', primary_key=True, serialize=False)),
                ('descricao_roupa', models.CharField(db_column='Descricao_Roupa', max_length=200)),
                ('quantidade_roupa', models.IntegerField(db_column='Quantidade_Roupa')),
                ('roupa_devolvida', models.IntegerField(db_column='Roupa_Devolvida')),
                ('roupa_lavanderia', models.IntegerField(db_column='Roupa_Lavanderia')),
            ],
            options={
                'db_table': 'Roupa_Paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaidaMedicamento',
            fields=[
                ('id_saida_medicamento', models.IntegerField(db_column='ID_Saida_Medicamento', primary_key=True, serialize=False)),
                ('data_saida', models.DateTimeField(db_column='Data_Saida')),
                ('valor_saida', models.DecimalField(blank=True, db_column='Valor_Saida', decimal_places=2, max_digits=8, null=True)),
                ('quantidade_de_gotas', models.IntegerField(blank=True, db_column='Quantidade_de_Gotas', null=True)),
            ],
            options={
                'db_table': 'Saida_Medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id_salario', models.IntegerField(db_column='ID_Salario', primary_key=True, serialize=False)),
                ('valor_salario', models.DecimalField(db_column='Valor_Salario', decimal_places=2, max_digits=8)),
                ('mes_inicio_vigencia_reajuste', models.CharField(db_column='Mes_Inicio_Vigencia_Reajuste', max_length=2)),
                ('ano_inicio_vigencia_reajuste', models.CharField(db_column='Ano_Inicio_Vigencia_Reajuste', max_length=4)),
                ('data_reajuste', models.DateField(db_column='Data_Reajuste')),
                ('porcentagem_reajuste', models.FloatField(db_column='Porcentagem_Reajuste')),
            ],
            options={
                'db_table': 'Salario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id_setor', models.IntegerField(db_column='ID_Setor', primary_key=True, serialize=False)),
                ('nome_setor', models.CharField(db_column='Nome_Setor', max_length=50)),
                ('descricao', models.CharField(db_column='Descricao', max_length=128)),
            ],
            options={
                'db_table': 'Setor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id_sindicato', models.IntegerField(db_column='ID_Sindicato', primary_key=True, serialize=False)),
                ('nome_sindicato', models.CharField(db_column='Nome_Sindicato', max_length=50)),
            ],
            options={
                'db_table': 'Sindicato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id_situacao', models.IntegerField(db_column='ID_Situacao', primary_key=True, serialize=False)),
                ('tipo_situacao', models.CharField(db_column='Tipo_Situacao', max_length=50)),
            ],
            options={
                'db_table': 'Situacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicoPlantao',
            fields=[
                ('id_atendimento_plantao_tecnico', models.IntegerField(db_column='ID_Atendimento_Plantao_Tecnico', primary_key=True, serialize=False)),
                ('data_atendimento', models.DateField(db_column='Data_Atendimento')),
                ('filestream_tecnico_plantao', models.CharField(db_column='FILESTREAM_Tecnico_Plantao', max_length=200)),
            ],
            options={
                'db_table': 'Tecnico_Plantao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAutorizacao',
            fields=[
                ('id_tipo_autorizacao', models.IntegerField(db_column='ID_Tipo_Autorizacao', primary_key=True, serialize=False)),
                ('nome_autorizacao', models.CharField(db_column='Nome_Autorizacao', max_length=50)),
            ],
            options={
                'db_table': 'Tipo_Autorizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCobranca',
            fields=[
                ('id_tipo_cobranca', models.IntegerField(db_column='ID_Tipo_Cobranca', primary_key=True, serialize=False)),
                ('nome_tipo_cobranca', models.CharField(db_column='Nome_Tipo_Cobranca', max_length=50)),
            ],
            options={
                'db_table': 'Tipo_Cobranca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDescontoGratificacao',
            fields=[
                ('id_tipo_desc_grat', models.IntegerField(db_column='ID_Tipo_Desc_Grat', primary_key=True, serialize=False)),
                ('nome_desconto_gratificacao', models.CharField(db_column='Nome_Desconto_Gratificacao', max_length=50)),
            ],
            options={
                'db_table': 'Tipo_Desconto_Gratificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id_tipo_medicamento', models.IntegerField(db_column='ID_Tipo_Medicamento', primary_key=True, serialize=False)),
                ('nome_tipo', models.CharField(db_column='Nome_tipo', max_length=50)),
            ],
            options={
                'db_table': 'Tipo_Medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoStatusAutorizacao',
            fields=[
                ('id_tipo_status_autorizacao', models.IntegerField(db_column='ID_Tipo_Status_Autorizacao', primary_key=True, serialize=False)),
                ('nome_tipo_status_autorizacao', models.CharField(db_column='Nome_Tipo_Status_Autorizacao', max_length=50)),
            ],
            options={
                'db_table': 'Tipo_Status_Autorizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id_treinamento', models.IntegerField(db_column='ID_Treinamento', primary_key=True, serialize=False)),
                ('nome_treinamento', models.CharField(db_column='Nome_Treinamento', max_length=50)),
                ('assunto_treinamento', models.CharField(db_column='Assunto_Treinamento', max_length=128)),
            ],
            options={
                'db_table': 'Treinamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TxtBrasindice',
            fields=[
                ('id_txt_brasindice', models.IntegerField(db_column='ID_Txt_Brasindice', primary_key=True, serialize=False)),
                ('filestream_brasindice', models.CharField(db_column='FILESTREAM_Brasindice', max_length=200)),
                ('data_inserida_brasindice', models.DateField(db_column='Data_Inserida_Brasindice')),
            ],
            options={
                'db_table': 'Txt_Brasindice',
                'managed': False,
            },
        ),
    ]
