# Generated by Django 2.1 on 2019-08-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndSignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicionalnoturno',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='arquivomedicoresponsavel',
            options={'managed': True},
        ),
    ]
