# Generated by Django 2.1 on 2019-08-31 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndSignUp', '0002_auto_20190831_0217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicionalnoturno',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='arquivomedicoresponsavel',
            options={'managed': True},
        ),
    ]
